### PR TITLE
Bundle relative paths

### PR DESCRIPTION
**Pull request by kjvalencik**
https://github.com/substack/bulkify/issues/2

### CODE REVIEW

**Comment by vvo** [comment]
@substack this is an interesting PR, having production code with absolute full path urls in the build is not great.

You endup having a build that look like:

```
({"components":({"blabla":require("/home/vvo/Dev/[...]
```

**Comment by substack** [comment]
This patch doesn't look correct. It only resolves files relative to the `dir` argument instead of resolving relative to the local file path, which is not how node modules work.

**Comment by vvo** [comment]
for anyone wondering @substack [solved this](https://github.com/substack/bulkify/issues/2#issuecomment-71522959)! Thanks.

**Comment by benjamine** [comment]
thanks!

**Comment by quicksnap** [comment]
Awesome!!


-Dan

On Tue, Jan 27, 2015 at 4:41 AM, Benjamín Eidelman <notifications@github.com

**Pull request closed without merging**
